environmentVariables:
  - name: "NETWORK_RPC"
    value: "https://rpc.testnet.fantom.network"
  - name: "NETWORK_CHAINID"
    value: "4002"
  - name: "CONTRACTADDRESS"
    value: "0xBA8A36804a6BaE272fe4C8A2F5Cf551b03C26A01"
  - name: "API_ENDPOINT"
    value: "https://api.testnet.artion.io"
  - name: "DECIMAL_ENDPOINT"
    value: "https://api.testnet.artion.io/getDecimals/"
